### ISSUE TITLE
Different Configuration for CUHK-SYSU and PRW

### ISSUE THREAD

**Issue by LuckyDC** [daodaofr/AlignPS#10]
Thanks for your great work! I find that the training configuration for CUHK-SYSU and PRW differs a lot. As shown in their config files, the code employ different type of bbox_head and weight_decay. Would you like to explain the reason behind such an implementation? Thanks a lot.

**Comment by daodaofr** [comment]
We tried different configurations for these two datasets, and we find the current configurations yield the best performance on these two datasets. But the impacts are minor, you can apply the PRW configuration to CUHK-SYSU, I think the difference is within 1%.

**Comment by LuckyDC** [comment]
Thanks for your reply. It addresses my concerns.
