### ISSUE TITLE
oim_tri.py

### ISSUE THREAD

**Issue by TragedyN** [daodaofr/AlignPS#11]
thx for your great work! I wonder if Class OIMLossNewFocal in oim_tri.py can be used as a loss to replace [oim.py] (https://github.com/DeanChan/NAE4PS/blob/master/lib/loss/oim.py) and how to used it

**Comment by daodaofr** [comment]
Thanks for your interest. I think it's possible to do that, but I have no plan to do it. You may try it.

**Comment by TragedyN** [comment]
ok, I will try

**Comment by sanghoooon** [comment]
@TragedyN Hi. I am also conducting experiments based on NAE, and was wondering the same thing. Have you tried?
