### ISSUE TITLE
Issue with results_1000.pkl when running    run_test_prw.sh!

### ISSUE THREAD

**Issue by YangJae96** [daodaofr/AlignPS#14]
![image](https://user-images.githubusercontent.com/57695621/124211383-f70d8d00-db27-11eb-8f21-0a7dae8b7f4e.png)

Hello,  I am getting error like this when I want to starting testing the model with pth file.
" FileNotFoundError: [Errno 2] No such file or directory: 'work_dirs/prw_dcn_base_focal_labelnorm_sub_ldcn_fg15_wd7-4/results_1000.pkl'" 

There is a dir work_dirs/prw_dcn_base_focal_labelnorm_sub_ldcn_fg15_wd7-4/ 
created when I run the training.

Do I need to wait until the training finish to obtain "results_1000.pkl"??
or How can I get results_1000.pkl? 

Thanks in advance.

**Comment by daodaofr** [comment]
please change the path to your trained model:
https://github.com/daodaofr/AlignPS/blob/98138c959059bc39e793a2a6dd164fba8388f19a/run_test_prw.sh#L9
