### ISSUE TITLE
Do you have any scripts for visible result?

### ISSUE THREAD

**Issue by HYERI520** [daodaofr/AlignPS#15]
Hello, I'm very new in this field.
And I want run and show the results by the images of the videos.
MMDetect provides some demos like image_demo.py or webcam_demo.py.
Do you have any scripts or code like this, or how can I get this?

Thank you for your helps.

**Comment by daodaofr** [comment]
I think you can directly use image_demo.py to visualize the results.

**Comment by HYERI520** [comment]
Thank you for your quick answer.

I tried like this.
>> python demo/image_demo.py demo/demo3.jpg configs/fcos/fcos_center- ... _dcn0.py work_dirs/fcos_center- ... _dcn0/latest.pth

But, when I tried I got error message belows

--------------------------------------------------------------------------------

Traceback (most recent call last):
  File "demo/image_demo.py", line 28, in <module>
    main()
  File "demo/image_demo.py", line 24, in main
    show_result_pyplot(model, args.img, result, score_thr=args.score_thr)
  File "/home/hyeri/work/AlignPS/mmdet/apis/inference.py", line 167, in show_result_pyplot
    img = model.show_result(img, result, score_thr=score_thr, show=False)
  File "/home/hyeri/work/AlignPS/mmdet/models/detectors/base.py", line 341, in show_result
    out_file=out_file)
  File "/home/hyeri/anaconda3/envs/work-jun/lib/python3.7/site-packages/mmcv/visualization/image.py", line 120, in imshow_det_bboxes
    assert bboxes.shape[1] == 4 or bboxes.shape[1] == 5
AssertionError

--------------------------------------------------------------------------------

Am I wrong?

Thank you for your helps.

**Comment by sunset233** [comment]
> demo/demo3.jpg configs/fcos/fcos_center- ... _dcn0.py work_dirs/fcos_center- ... _dcn0/latest.pth

Hello, Have you solve the problem? I am encountered the same problem, could you please tell me the solution?

**Comment by daodaofr** [comment]
This is because we concatenate the reid features with box results, to solve this. You can simply find the boxes results and replace it with boxes = boxes[:, :5].

Or you can replace this line:
https://github.com/daodaofr/AlignPS/blob/c20cf329b2934a8693e2064435d3e3f65c496095/mmdet/models/detectors/single_stage_reid.py#L123

with:
https://github.com/daodaofr/AlignPS/blob/c20cf329b2934a8693e2064435d3e3f65c496095/mmdet/models/detectors/single_stage.py#L119

**Comment by HYERI520** [comment]
Thanks for your solution,
but it is not still worked.

I get the bbox_results is 2D-array but it contains 2D numpy.ndarray.
Also I don't get the meaning of boxes results.
How does it consist of? Cause I cannot find the information like bbox coordinates at the bbox results.

**Comment by HYERI520** [comment]
I solve this.

Add "boxes = boxes[:, :5]" below.
https://github.com/daodaofr/AlignPS/blob/98138c959059bc39e793a2a6dd164fba8388f19a/mmdet/models/detectors/base.py#L300

Thank you.
