### ISSUE TITLE
The implemention of scale alignment

### ISSUE THREAD

**Issue by qixiong-wang** [daodaofr/AlignPS#18]
Hi, thanks for your excellent work. However, I have some question about the implemention of scale alignment.
In your paper, it is said that you only make predictions based on a single layer of AFA. But in the forward function of `mmdet/models/dense_heads/fcos_reid_head_focal_sub_triqueue.py`, feature of different FPN level are all used for detection and reid. 
I am looking forward to your reply.

**Comment by daodaofr** [comment]
https://github.com/daodaofr/AlignPS/blob/98138c959059bc39e793a2a6dd164fba8388f19a/mmdet/models/dense_heads/fcos_reid_head_focal_sub_triqueue.py#L66

Here, only the first scale is utilized.

**Comment by qixiong-wang** [comment]
I got it. Thanks for your reply.
