### ISSUE TITLE
run_test_prw.sh   prw_alignps_plus.pth is not a check point file

### ISSUE THREAD

**Issue by FeboReigns** [daodaofr/AlignPS#29]
when I run  "run_test_prw.sh",  there is an error "prw_alignps_plus.pth is not a check point file"

![20220329172957](https://user-images.githubusercontent.com/101039128/160580862-46bcefab-a364-4f79-be8a-4c39f8c50572.png)

**Comment by crsm424** [comment]
Hi, how did you solve this problem
