### ISSUE TITLE
Why only use focal and triplet loss in AlignPS branch

### ISSUE THREAD

**Issue by HanGuangXin** [daodaofr/AlignPS#31]
Hi, thanks for your awesome work.

I noticed that the focal and triplet loss are only used in AlignPS branch, not used in RoI-Align branch. And I don't really understand this setting.

But I have a explanation. The reason is positive samples in AlignPS branch (FCOS center 3x3 area) is much more than them in RoI-Align branch (positive proposals). So in AlignPS branch, for focal loss, features from neighbor location is similar and contain many easy samples. For triplet loss, it is much easier to build triplets with more samples.

Looking forward to your reply. Thanks in advance!

**Comment by daodaofr** [comment]
Thanks for this great point. Actually, the focal and triplet loss inherit from our conference paper "Anchor-free person search". While in our extension, we add the RoI-Align branch, which shares similar spirits with the traditional two-stage frameworks, e.g., OIM and SeqNet. To make a fair comparison, we only didn't use focal and triplet. I think it may also work to add them.

**Comment by HanGuangXin** [comment]
I see. Thanks for your reply!
