### ISSUE TITLE
A Question about the Unlabedmatching

### ISSUE THREAD

**Issue by hh23333** [daodaofr/AlignPS#7]
Thanks for sharing you excellent work! I have a question about the update function of unlabeled queue: 
https://github.com/daodaofr/AlignPS/blob/657d49bfe295f5e58b66957891b858c9a39d3fa4/mmdet/models/dense_heads/unlabeled_matching_layer.py#L32
Why only update the front 64 channels of unlabeled queue? Does it bring any performance improvements?

**Comment by daodaofr** [comment]
We follow this implementation:
https://github.com/serend1p1ty/person_search/blob/123383661fc38aef486f538bf0024235c14f7fec/lib/oim/unlabeled_matching_layer.py#L31

We didn't modify that, maybe you could try. I think the impact would be limited.

**Comment by hh23333** [comment]
Got it! Thanks
