### ISSUE TITLE
No such file or directory: '....../annotation/test/train_test/TestG100.mat'

### ISSUE THREAD

**Issue by CharlesChen24** [daodaofr/AlignPS#8]
when i run 'bash run_test.sh', I can get results_1000.pkl successfully. However, there is a FileNotFoundError after that. There are not data, of which the structrue is like '.mat' in CUHK-SYSU. I will appreciate it if you can help.

Traceback (most recent call last):
  File "***/yes/lib/python3.7/site-packages/scipy/io/matlab/mio.py", line 33, in _open_file
    return open(file_like, 'rb'), True
FileNotFoundError: [Errno 2] No such file or directory: '***/data/CUHK-SYSU/annotation/test/train_test/TestG100.mat'

**Comment by daodaofr** [comment]
This is the annotation file in CUHK-SYSU dataset, please make sure this file exists in your path.

https://github.com/daodaofr/AlignPS/blob/657d49bfe295f5e58b66957891b858c9a39d3fa4/tools/test_results.py#L94

**Comment by CharlesChen24** [comment]
Maybe CUHK-SYSU dataset I downloaded from the Internet is not complete. Is the right method to sent an email to sli@ee.cuhk.edu.hk？I have done it, but get no reply the whole day. I'm sorry to ask, can you provide me with it in some ways? Thanks a lot.

**Comment by daodaofr** [comment]
Uploaded, lease find in "demo/anno/cuhk-sysu".

**Comment by yangyangkiki** [comment]
Hi I found a problem when training the cuhk dataset like this:

FileNotFoundError: [Errno 2] No such file or directory: '/home/yy1/2021/data/cuhk/annotation/train_pid_new.json'

How can I change the root_dir ' /home/yy1/2021/data/cuhk/ ' to my own path?

Beacuse I can not find the root dir in 'fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_dcn0.py'

Thanks a lot.

**Comment by CharlesChen24** [comment]
AlignPS/configs/_base_/datasets/cuhk_detection_1000.py

**Comment by yangyangkiki** [comment]
Thank you so much!

**Comment by CharlesChen24** [comment]
Dear author. I have got real dataset, However, I still have some questions about "Train.mat" now, Did you produce 'train_pid_new.json' by using 'Train.mat'？I am very interested in the scripts for preprocessing dataset. Could you provide it please? Thanks and looking forward to your reply.

**Comment by daodaofr** [comment]
I no longer have it. Please refer to these two links.
https://github.com/DeanChan/NAE4PS/blob/master/lib/datasets/cuhk_sysu.py
https://blog.csdn.net/qq_26815239/article/details/89312881

**Comment by CharlesChen24** [comment]
Thank you for your kindness and generosity sincerely！
